---
- name: Ensure prerequisites packages exist
  ansible.builtin.apt:
    pkg:
      - gnupg
      - curl
      - debian-archive-keyring
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: true

- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install boto3
  ansible.builtin.apt:
    name: python3-boto3
    state: present

- name: Install AWS CLI
  ansible.builtin.apt:
    name: awscli
    state: latest    

- name: Install Java JDK 17
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present